### ISSUE TITLE
怎么生成新的ofd文件？

### ISSUE THREAD

**Issue by XiangLiAn627** [swpudp/OfdSharp#1]
作者能不能写一下怎么生成OFD文件，我看了下代码好像没有找到，完善下说明文档可以嘛，谢谢了

**Comment by swpudp** [comment]
实在抱歉，生成ofd文件还没开发完，该类库目前只应用在发票ofd文件的读取和验真。



swpudp@163.com
 
发件人： XiangLiAn627
发送时间： 2021-01-18 23:30
收件人： swpudp/OfdSharp
抄送： Subscribed
主题： [swpudp/OfdSharp] 怎么生成新的ofd文件？ (#1)
作者能不能写一下怎么生成OFD文件，我看了下代码好像没有找到，完善下说明文档可以嘛，谢谢了

**Comment by XiangLiAn627** [comment]
好的感谢，我会持续关注该项目的

**Comment by swpudp** [comment]
目前只应用在发票ofd文件的读取和验真
